CREATE TABLE TODO_USERS (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(255) NOT NULL,
    USER_PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE USER_COOKIES (
    USER_COOKIES_ID INT AUTO_INCREMENT PRIMARY KEY,
    COOKIE_NAME VARCHAR(255) NOT NULL,
    COOKIE_VALUE VARCHAR(255) NOT NULL,
    USER_ID INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES TODO_USERS(USER_ID)
);

CREATE TABLE TASKS (
    TASK_ID INT PRIMARY KEY AUTO_INCREMENT,
      USER_ID INT NOT NULL,
    TASK_NAME VARCHAR(255) NOT NULL,
    DUE_DATE DATE,
    DUE_TIME TIME,
    PRIORITY VARCHAR(50),
    FOREIGN KEY (USER_ID) REFERENCES TODO_USERS(USER_ID)
);
