-- EMPLOYEE TABLE
CREATE TABLE IF NOT EXISTS EMPLOYEE (
    EMP_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    DOB DATE,
    PHONE_NUMBER BIGINT,
    EMAIL VARCHAR(255),
    MANAGER_ID INT,
    GENDER ENUM('MALE', 'FEMALE', 'OTHER') DEFAULT 'OTHER',
    ROLE VARCHAR(255),
    FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEE(EMP_ID)
);


-- EMPLOYEE_PASSWORD TABLE
CREATE TABLE IF NOT EXISTS EMPLOYEE_PASSWORD (
    EMPLOYEE_PASSWORD_ID INT AUTO_INCREMENT PRIMARY KEY,
    EMP_ID INT,
    EMAIL_ID VARCHAR(255),
    PASSWORD VARCHAR(255),
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
);

-- LEAVE_TYPE TABLE
| CREATE TABLE `LEAVE_TYPE` (
  `LEAVE_TYPE_ID` int NOT NULL AUTO_INCREMENT,
  `LEAVE_TYPE` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(1000) DEFAULT NULL,
  `MAX_LEAVE_DAYS_ALLOWED` int DEFAULT NULL,
  `APPLICABLE_GENDER` enum('MALE','FEMALE','BOTH') DEFAULT 'BOTH',
  PRIMARY KEY (`LEAVE_TYPE_ID`)

-- LEAVE_REQUEST TABLE
CREATE TABLE IF NOT EXISTS LEAVE_REQUEST (
    LEAVE_REQUEST_ID INT NOT NULL AUTO_INCREMENT,
    EMP_ID INT DEFAULT NULL,
    LEAVE_TYPE_ID INT DEFAULT NULL,
    LEAVE_REASON VARCHAR(1000) DEFAULT NULL,
    FROM_DATE DATE DEFAULT NULL,
    TO_DATE DATE DEFAULT NULL,
    DATE_OF_APPLICATION DATE DEFAULT NULL,
    LEAVE_STATUS ENUM('APPROVED', 'REJECTED', 'PENDING', 'CANCELLED') DEFAULT NULL,
    DATE_OF_ACTION DATE DEFAULT NULL,
    PRIMARY KEY (LEAVE_REQUEST_ID),
    KEY EMP_ID (EMP_ID),
    KEY LEAVE_TYPE_ID (LEAVE_TYPE_ID),
    CONSTRAINT LEAVE_REQUEST_IBFK_1 FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID),
    CONSTRAINT LEAVE_REQUEST_IBFK_2 FOREIGN KEY (LEAVE_TYPE_ID) REFERENCES LEAVE_TYPE (LEAVE_TYPE_ID)
);

-- USER_COOKIES TABLE
CREATE TABLE IF NOT EXISTS EMPLOYEE_COOKIES (
    EMPLOYEE_COOKIES_ID INT AUTO_INCREMENT PRIMARY KEY,
    COOKIE_NAME VARCHAR(255) NOT NULL,
    COOKIE_VALUE VARCHAR(255) NOT NULL,
    EMP_ID INT NOT NULL,
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
);
